// <auto-generated />
using System;
using CasaBeneditaMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasaBeneditaMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430175422_SeedNovosProdutos")]
    partial class SeedNovosProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasaBeneditaMVC.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Nome = "Entradas"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Nome = "Pratos Principais"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Nome = "Bebidas"
                        },
                        new
                        {
                            CategoriaId = 4,
                            Nome = "Sobremesas"
                        });
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesaId"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.HasKey("MesaId");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            MesaId = 1,
                            Capacidade = 4,
                            Disponivel = true,
                            NumeroMesa = 1
                        },
                        new
                        {
                            MesaId = 2,
                            Capacidade = 4,
                            Disponivel = true,
                            NumeroMesa = 2
                        },
                        new
                        {
                            MesaId = 3,
                            Capacidade = 4,
                            Disponivel = true,
                            NumeroMesa = 3
                        },
                        new
                        {
                            MesaId = 4,
                            Capacidade = 4,
                            Disponivel = true,
                            NumeroMesa = 4
                        },
                        new
                        {
                            MesaId = 5,
                            Capacidade = 4,
                            Disponivel = true,
                            NumeroMesa = 5
                        },
                        new
                        {
                            MesaId = 6,
                            Capacidade = 4,
                            Disponivel = true,
                            NumeroMesa = 6
                        });
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = 1,
                            Descricao = "Entrada leve com pão e tomate",
                            Disponivel = true,
                            ImagemUrl = "Entradas/Bruschetta.png",
                            Nome = "Bruschetta Benedita",
                            Preco = 24.90m
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = 1,
                            Descricao = "Finas fatias de carne",
                            Disponivel = true,
                            ImagemUrl = "Entradas/Carpaccio.png",
                            Nome = "Carpaccio Especial da Casa",
                            Preco = 29.90m
                        },
                        new
                        {
                            ProdutoId = 3,
                            CategoriaId = 1,
                            Descricao = "Batatas crocantes",
                            Disponivel = true,
                            ImagemUrl = "Entradas/Batata.png",
                            Nome = "Batata Rústica da Dona Benedita",
                            Preco = 19.90m
                        },
                        new
                        {
                            ProdutoId = 4,
                            CategoriaId = 1,
                            Descricao = "Bolinho crocante",
                            Disponivel = true,
                            ImagemUrl = "Entradas/Bolinho.png",
                            Nome = "Bolinho Dourado da Vovó",
                            Preco = 22.90m
                        },
                        new
                        {
                            ProdutoId = 5,
                            CategoriaId = 1,
                            Descricao = "Petisco especial",
                            Disponivel = true,
                            ImagemUrl = "Entradas/Dadinhos.png",
                            Nome = "Dadinhos Crocantes da Casa",
                            Preco = 21.90m
                        },
                        new
                        {
                            ProdutoId = 6,
                            CategoriaId = 2,
                            Descricao = "Carne grelhada especial",
                            Disponivel = true,
                            ImagemUrl = "Pratos/picanha.png",
                            Nome = "Picanha da Dona Benedita",
                            Preco = 64.90m
                        },
                        new
                        {
                            ProdutoId = 7,
                            CategoriaId = 2,
                            Descricao = "Costela suculenta",
                            Disponivel = true,
                            ImagemUrl = "Pratos/Costela.png",
                            Nome = "Costela da Casa",
                            Preco = 61.90m
                        },
                        new
                        {
                            ProdutoId = 8,
                            CategoriaId = 2,
                            Descricao = "Filé com molho especial",
                            Disponivel = true,
                            ImagemUrl = "Pratos/FileMignon.png",
                            Nome = "Filé Mignon",
                            Preco = 69.90m
                        },
                        new
                        {
                            ProdutoId = 9,
                            CategoriaId = 2,
                            Descricao = "Carne na brasa",
                            Disponivel = true,
                            ImagemUrl = "Pratos/contra.png",
                            Nome = "Contra Filé",
                            Preco = 49.90m
                        },
                        new
                        {
                            ProdutoId = 10,
                            CategoriaId = 2,
                            Descricao = "Lombo assado",
                            Disponivel = true,
                            ImagemUrl = "Pratos/Lombo.png",
                            Nome = "Lombo Suíno",
                            Preco = 44.90m
                        });
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorarioReserva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusReserva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("MesaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Produto", b =>
                {
                    b.HasOne("CasaBeneditaMVC.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Reserva", b =>
                {
                    b.HasOne("CasaBeneditaMVC.Models.Mesa", "Mesa")
                        .WithMany("Reservas")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasaBeneditaMVC.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Mesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Mesa", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
