// <auto-generated />
using System;
using CasaBeneditaMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasaBeneditaMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasaBeneditaMVC.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Nome = "Entradas"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Nome = "Pratos Principais"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Nome = "Bebidas"
                        },
                        new
                        {
                            CategoriaId = 4,
                            Nome = "Sobremesas"
                        });
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesaId"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.HasKey("MesaId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            CategoriaId = 1,
                            Descricao = "Entrada leve com pão e tomate",
                            Disponivel = true,
                            ImagemUrl = "Entradas/Bruschetta.png",
                            Nome = "Bruschetta Benedita",
                            Preco = 24.90m
                        },
                        new
                        {
                            ProdutoId = 2,
                            CategoriaId = 1,
                            Descricao = "Finas fatias de carne",
                            Disponivel = true,
                            ImagemUrl = "Entradas/Carpaccio.png",
                            Nome = "Carpaccio Especial da Casa",
                            Preco = 29.90m
                        },
                        new
                        {
                            ProdutoId = 3,
                            CategoriaId = 1,
                            Descricao = "Batatas crocantes",
                            Disponivel = true,
                            ImagemUrl = "Entradas/Batata.png",
                            Nome = "Batata Rústica da Dona Benedita",
                            Preco = 19.90m
                        },
                        new
                        {
                            ProdutoId = 4,
                            CategoriaId = 1,
                            Descricao = "Bolinho crocante",
                            Disponivel = true,
                            ImagemUrl = "Entradas/Bolinho.png",
                            Nome = "Bolinho Dourado da Vovó",
                            Preco = 22.90m
                        },
                        new
                        {
                            ProdutoId = 5,
                            CategoriaId = 1,
                            Descricao = "Petisco especial",
                            Disponivel = true,
                            ImagemUrl = "Entradas/Dadinhos.png",
                            Nome = "Dadinhos Crocantes da Casa",
                            Preco = 21.90m
                        },
                        new
                        {
                            ProdutoId = 6,
                            CategoriaId = 2,
                            Descricao = "Carne grelhada especial",
                            Disponivel = true,
                            ImagemUrl = "Pratos/picanha.png",
                            Nome = "Picanha da Dona Benedita",
                            Preco = 64.90m
                        },
                        new
                        {
                            ProdutoId = 7,
                            CategoriaId = 2,
                            Descricao = "Costela suculenta",
                            Disponivel = true,
                            ImagemUrl = "Pratos/Costela.png",
                            Nome = "Costela da Casa ao Molho Barbecue",
                            Preco = 61.90m
                        },
                        new
                        {
                            ProdutoId = 8,
                            CategoriaId = 2,
                            Descricao = "Filé com molho especial",
                            Disponivel = true,
                            ImagemUrl = "Pratos/FileMignon.png",
                            Nome = "Filé Mignon ao Molho da Vovó",
                            Preco = 69.90m
                        },
                        new
                        {
                            ProdutoId = 9,
                            CategoriaId = 2,
                            Descricao = "Carne na brasa",
                            Disponivel = true,
                            ImagemUrl = "Pratos/contra.png",
                            Nome = "Contra Filé Especial na Brasa",
                            Preco = 49.90m
                        },
                        new
                        {
                            ProdutoId = 10,
                            CategoriaId = 2,
                            Descricao = "Lombo assado",
                            Disponivel = true,
                            ImagemUrl = "Pratos/Lombo.png",
                            Nome = "Lombo Suíno Assado da Fazenda",
                            Preco = 44.90m
                        },
                        new
                        {
                            ProdutoId = 11,
                            CategoriaId = 4,
                            Descricao = "Sobremesa da casa",
                            Disponivel = true,
                            ImagemUrl = "Sobremesas/Pudim.png",
                            Nome = "Pudim Cremoso da Dona Benedita",
                            Preco = 12.00m
                        },
                        new
                        {
                            ProdutoId = 12,
                            CategoriaId = 4,
                            Descricao = "Brownie quente",
                            Disponivel = true,
                            ImagemUrl = "Sobremesas/Brownie.png",
                            Nome = "Brownie Quentinho da Casa",
                            Preco = 18.90m
                        },
                        new
                        {
                            ProdutoId = 13,
                            CategoriaId = 4,
                            Descricao = "Mousse cremoso",
                            Disponivel = true,
                            ImagemUrl = "Sobremesas/Mousse.jpg",
                            Nome = "Mousse de Chocolate Especial",
                            Preco = 14.90m
                        },
                        new
                        {
                            ProdutoId = 14,
                            CategoriaId = 4,
                            Descricao = "Sobremesa com frutas",
                            Disponivel = true,
                            ImagemUrl = "Sobremesas/DoceTentacao.png",
                            Nome = "Doce Tentação de Frutas Vermelhas",
                            Preco = 19.90m
                        },
                        new
                        {
                            ProdutoId = 15,
                            CategoriaId = 4,
                            Descricao = "Chocolate especial",
                            Disponivel = true,
                            ImagemUrl = "Sobremesas/DeliciaChocolate.png",
                            Nome = "Delícia de Chocolate com Coração Quente",
                            Preco = 22.90m
                        },
                        new
                        {
                            ProdutoId = 16,
                            CategoriaId = 3,
                            Descricao = "Lata 350ml",
                            Disponivel = true,
                            ImagemUrl = "Bebidas/refri_latas.jpg",
                            Nome = "Refrigerante Gelado",
                            Preco = 6.00m
                        },
                        new
                        {
                            ProdutoId = 17,
                            CategoriaId = 3,
                            Descricao = "Suco natural",
                            Disponivel = true,
                            ImagemUrl = "Bebidas/Suco.png",
                            Nome = "Suco Natural da Casa",
                            Preco = 9.90m
                        },
                        new
                        {
                            ProdutoId = 18,
                            CategoriaId = 3,
                            Descricao = "Água sem gás",
                            Disponivel = true,
                            ImagemUrl = "Bebidas/Agua.png",
                            Nome = "Água Mineral",
                            Preco = 4.00m
                        },
                        new
                        {
                            ProdutoId = 19,
                            CategoriaId = 3,
                            Descricao = "Cerveja gelada",
                            Disponivel = true,
                            ImagemUrl = "Bebidas/Cervejas.png",
                            Nome = "Cerveja Long Neck",
                            Preco = 8.00m
                        },
                        new
                        {
                            ProdutoId = 20,
                            CategoriaId = 3,
                            Descricao = "Cerveja especial",
                            Disponivel = true,
                            ImagemUrl = "Bebidas/Cervejas.png",
                            Nome = "Cerveja Artesanal da Casa",
                            Preco = 14.00m
                        });
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorarioReserva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusReserva")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservaId");

                    b.HasIndex("MesaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Produto", b =>
                {
                    b.HasOne("CasaBeneditaMVC.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Reserva", b =>
                {
                    b.HasOne("CasaBeneditaMVC.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("CasaBeneditaMVC.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
